apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-backend.fullname" . }}
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "todo-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- include "todo-backend.podAnnotations" . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "todo-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "todo-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo-backend.fullname" . }}-db-secret
                  key: dbHost
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo-backend.fullname" . }}-db-secret
                  key: dbName
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo-backend.fullname" . }}-db-secret
                  key: dbUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo-backend.fullname" . }}-db-secret
                  key: dbPassword
            - name: DB_SSL_MODE
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo-backend.fullname" . }}-db-secret
                  key: dbSslMode
            {{- if .Values.env }}
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}