{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-backend.fullname" . }}-db-secret
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
type: Opaque
data:
  dbHost: {{ .Values.secrets.dbHost | b64enc | quote }}
  dbName: {{ .Values.secrets.dbName | b64enc | quote }}
  dbUser: {{ .Values.secrets.dbUser | b64enc | quote }}
  dbPassword: {{ .Values.secrets.dbPassword | b64enc | quote }}
  dbSslMode: {{ .Values.secrets.dbSslMode | b64enc | quote }}
{{- end }}