{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-frontend.fullname" . }}-app-secret
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
type: Opaque
data:
  nextAuthSecret: {{ .Values.secrets.nextAuthSecret | b64enc | quote }}
  nextAuthUrl: {{ .Values.secrets.nextAuthUrl | b64enc | quote }}
{{- end }}